version: "3.3"

services:
  app:
    build: .
    container_name: app

    ports:
      - "3000:3000"

    networks:
      - web
      - backend

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongo"
      - "MONGO_INITDB_ROOT_PASSWORD=123"

    networks:
      - backend

networks:
  web:
    external: true

  backend:
    driver: bridge